#VERBOSE = 1
OUTNAME_RELEASE = main
OUTNAME_DEBUG   = main_debug
CUSTOM_INCPATHS = ../include
CUSTOM_SRCPATHS = ../src/trtcommon ../src/task ../src/plugin ../src/utils
MAKEFILE ?= ../Makefile.config
include $(MAKEFILE)
